### ISSUE TITLE
If FPort does not exist in the packet, getFPort() throws an exception

### ISSUE THREAD

**Issue by rerickson1** [anthonykirby/lora-packet#12]
https://github.com/anthonykirby/lora-packet/blob/054cc726a21cc759820c938faca20b02f0c884b2/lib/packet.js#L348

A check to see if FPort exists should be added to the function.  If FPort does not exist, just return null.

**Comment by anthonykirby** [comment]
(I'm scheduling time in September to work on this; apologies for the delay)
