### ISSUE TITLE
Decrypted string shows random characters.

### ISSUE THREAD

**Issue by sudhamsursr** [anthonykirby/lora-packet#14]
I have tried decrypting a payload. In this process, the decoding is successful, **MIC Check** came to be "OK".
**packet MIC** and **calculated MIC** came out to be identical.
But the Decrypted messages shows random values like **�!\u0000** or **\t** etc.

Here is the sample data that I have used for decryption.

Payload: 402B19012600040001B2E2E4F81F44B6
NetworkSKey: EA68299F93F4AB9886D36755E7E23FC3
AppSKey: 57D69E5DE46FEAF8B5FBF6CC1F436B58

Output:

      "packet.toString()=\nMessage Type = …CK = false\n FCtrl.ADR = false\n"

      packet.toString()=
      Message Type = Data
      PHYPayload = 402B19012600040001B2E2E4F81F44B6

      ( PHYPayload = MHDR[1] | MACPayload[..] | MIC[4] )
      MHDR = 40
      MACPayload = 2B19012600040001B2E2E4
      MIC = F81F44B6

     ( MACPayload = FHDR | FPort | FRMPayload )
     FHDR = 2B190126000400
     FPort = 01
     FRMPayload = B2E2E4

     ( FHDR = DevAddr[4] | FCtrl[1] | FCnt[2] | FOpts[0..15] )
     DevAddr = 2601192B (Big Endian)
     FCtrl = 00
     FCnt = 0004 (Big Endian)
     FOpts = 

     Message Type = Unconfirmed Data Up
     Direction = up
     FCnt = 4
     FCtrl.ACK = false
     FCtrl.ADR = false

    "packet MIC=f81f44b6"
    "FRMPayload=b2e2e4"
    "MIC check=OK"
    "calculated MIC=f81f44b6"
    "Decrypted='�!\u0000'"

The actual data sent from the node is a number - "222555".

1. What is the data type of the final output? How can I convert it to get the actual payload?
2. Am I missing something in the whole process of decryption?
3. What is MIC here?

Tried on npm Runkit: https://npm.runkit.com/lora-packet

**Comment by avbentem** [comment]
This is not a bug. When using the example code then just add `'hex'` to the `toString()` to see you've actually sent 3 bytes that in hexadecimal could be printed as `0xe52100`. Without knowing how your node encoded its payload, this library cannot help you decode this.

```javascript
console.log("Decrypted='" + lora_packet.decrypt(packet, AppSKey, NwkSKey).toString('hex') + "'");
```

See https://www.thethingsnetwork.org/docs/devices/bytes.html and https://www.thethingsnetwork.org/forum/t/decrypting-messages-for-dummies/4894/4

**Comment by anthonykirby** [comment]
It isn't possible to change the code without breaking functionality.  I've improved the documentation.
