### ISSUE TITLE
Error on decoding

### ISSUE THREAD

**Issue by makniZ** [anthonykirby/lora-packet#15]
Hi,
I have a MAC payload "0307" which is normaly a "UnconfirmedDataUp". But the decoding function return a Mtype = Join Request.

Any idea please ?

Thx

**Comment by avbentem** [comment]
The message type is not in the MAC Payload, but in the 1 byte Message Header, MHDR. 

`0x0307` is `%0000 0011 0000 0111`, and `000` is a Join Request:

> **4.2.1 Message type (MType bit field)**
>
> The LoRaWAN distinguishes between six different MAC message types: join request, join accept, unconfirmed data up/down, and confirmed data up/down.
>
> | MType | Description           |
> |-------|-----------------------|
> | 000   | Join Request          |
> | 001   | Join Accept           |
> | 010   | Unconfirmed Data Up   |
> | 011   | Unconfirmed Data Down |
> | 100   | Confirmed Data Up     |
> | 101   | Confirmed Data Down   |
> | 110   | RFU                   |
> | 111   | Proprietary           |

**Comment by makniZ** [comment]
hi 
Thanks for the answer ! I did not understand why do we have to convert 03 to binary ?

thx

**Comment by avbentem** [comment]
First things first: please answer my question instead:

> Why do you think this should indicate an unconfirmed uplink?

**Comment by makniZ** [comment]
No i did a mistake !

**Comment by avbentem** [comment]
Hexadecimal `0x0307` is just one of the many ways to display the bits `0000 0011 0000 0111`. One could also write it as decimal 775, as octal 01407<sup>†</sup>, and [many more](https://en.wikipedia.org/wiki/List_of_numeral_systems)... 

As the MType in the table above only looks at 3 bits, it's easier to use `%0000 0011` rather than `0x0307`. That's all.

---
<sup>†</sup> octal 01407 itself could also be written as `0o1407`, `o1407`, `1407o`, `q1407`, 1407₈, 1407₍₈₎ and many other ways

**Comment by makniZ** [comment]
thanks ! is there a way to decode only the mac payload ?

**Comment by avbentem** [comment]
Please get your terminology right; a 2 byte message cannot be a MAC Payload of an uplink.

Like I wrote before:

> This library works on full LoRaWAN packets.

It cannot decode your application payload, if that's what you're referring to with "MAC payload", which is really much more than just the application payload:

> **4.3  MAC Payload of Data Messages (MACPayload)** 
>
> The MAC payload of the data messages, a so-called “data frame”, contains a frame header  (**FHDR**)  followed  by  an  optional  port field  (**FPort**)  and  an  optional  frame payload  field  (**FRMPayload**).

If you're indeed asking about the application payload (FRMPayload) then, if you're using The Things Network, see https://www.thethingsnetwork.org/forum/t/is-there-any-documentation-on-payload-functions/3441 and the many links there.
