### ISSUE TITLE
Packet decoding as a service

### ISSUE THREAD

**Issue by ktsakos** [anthonykirby/lora-packet#21]
Could i use this library as a service? Essentially, i would like to send the phy payload that my mqtt broker receives from my gateway to the cloud. Then i would like to make requests to the service with the phy payload as input and then it could return me as json format the output with the decoded and decrypted lora packet information.Is is feasible?

**Comment by anthonykirby** [comment]
Sure, it's MIT licenced; you can do whatever you want!
