### ISSUE TITLE
About the payload from different sensors

### ISSUE THREAD

**Issue by ktsakos** [anthonykirby/lora-packet#24]
I have the Nexus Demoboard from ideetron which sends some temperature and humidity measures at a specific logic for the Things Network  and the Cayenne Dashboard.

If i choose to buy customed temperature/humidity sensors , they will send a payload at a different logic and they cannot be configured.

Do you think that i have to use the same sensors for my app in order to receive the same type of payload at the uplink?

**Comment by anthonykirby** [comment]
this issue board is a place to discuss and report issues for this specific node.js library.  It's not a general support forum.
