### ISSUE TITLE
Support of LoRaWAN 1.0.1 final

### ISSUE THREAD

**Issue by tortizactility** [anthonykirby/lora-packet#25]
As I can see on the README.md, the current implementation is based on LoRaWAN 1.0.1 draft 3.
I did first a quick comparison between LW 1.0.1 draft 3 and the final version:
https://www.draftable.com/compare/aywIsYazscsj

Here are the main differences (very few):
- General refactoring and typo correction
- New paragraph page 20 to explain that FPort 224 is dedicated LoRaWAN Mac layer test protocol
 when draft 3 just say that FPort 224 to 255 are reserved
- RXParamSetupAns and RXTimingSetupAns but there is no impact on packet parsing or generation.

By checking quickly the difference it will be possible to say that the lora-packet module is LW 1.0.1 compliant

**Comment by anthonykirby** [comment]
I've updated the docs, many thanks!
