### ISSUE TITLE
Support of LoRaWAN 1.0.2

### ISSUE THREAD

**Issue by tortizactility** [anthonykirby/lora-packet#26]
Like the issue#25, I did another comparison between LW 1.0.1 final and the 1.0.2 final version:
https://www.draftable.com/compare/xbpYDtNRPAPH

Here are the main differences :

- Physical layer moved to a dedicated document named "Regional Parameters" (last version for LW 1.0.2 (RevC) in attachment
[LoRaWAN Regional Parameters v1.0.2_revB.pdf](https://github.com/anthonykirby/lora-packet/files/2009086/LoRaWAN.Regional.Parameters.v1.0.2_revB.pdf)
- Some typo correction and refactoring
- Two new MAC commands: (0x0A) DlChannelReq/Ans and (0x09) TxParamSetupReq/Ans
- Clarification regarding AppKey
- The end-device is able to process multiples ADRReq in a single block

It's not a big deal to be 1.0.2 compliant and I can help you to do it

**Comment by anthonykirby** [comment]
thank you, I've updated the docs.  Our library doesn't (yet!) support the decoding of MAC commands, so the changes for 1.0.2 don't affect it.
