### ISSUE TITLE
Where to find Nwskey and Appskey

### ISSUE THREAD

**Issue by OPCUAUser** [anthonykirby/lora-packet#38]
Hi,

I am new to LoRaWAN. I have a lora packet, where I have to provide the Nwskey and Appskey for the tool to decrypt my data. Could any one help me locate the Appskey and Nwskey of the communication. Where can i find the same in my gateway/application?

Your support is required!

Thanks.

**Comment by anthonykirby** [comment]
Hi OPCUAUser,
If you've only got a captured packet, you won't be able to get the keys from it - that's the purpose of the security model.
The LoRA providers often publish helpful documentation about this, for example [The Things Network](https://www.thethingsnetwork.org/docs/lorawan/security.html) & [AllThingsTalk](https://docs.allthingstalk.com/tutorials/lora-keys/)
