### ISSUE TITLE
Typescript and support for modern Node.js API

### ISSUE THREAD

**Issue by felipefdl** [anthonykirby/lora-packet#40]
hi @anthonykirby, I'm the software architect at [TagoIO](https://tago.io), the lora-packet is amazing, we would like to use the library on our Payload Parser feature, however, we use typescript types for auto-completion on our front-end (online editor) also the current version is using deprecated API from Node.js as **new Buffer()**. So, we have rewritten the library to use Typescript and fix it to use new Node.js API (>10.x), also it keeps the same functions, same arguments, totally compatible, so I would like to know if you have the interest to merge both projects to avoid unnecessary fragmentation.

Thanks.

**Comment by anthonykirby** [comment]
Hi Felipe,
yes, I'm keen to avoid duplication & I'm happy to work with you to keep lora-packet up to date!
thanks
Anthony

**Comment by felipefdl** [comment]
Ok, great! our team is working on PR. thanks!

**Comment by anthonykirby** [comment]
thank you for the PR - it was a pleasure to review & merge :grin: 

p.s. I still have very happy memories of visiting Sao Paolo, over 25 years ago!

**Comment by felipefdl** [comment]
Thank you @anthonykirby, if you need anything from TagoIO tell me!

Our team will be always keep eye on LoRa technologies and libraries, if you need help to do anything, we are ready to help!

Brazil is always open to good people, come whenever you want, I know you will be welcomed!, SP from 25 years ago is so different than now, I think next year it will be a good place to revisiting.
