### ISSUE TITLE
Could you explain this error, please.

### ISSUE THREAD

**Issue by tony1tf** [anthonykirby/lora-packet#50]
Error (lora-packet verify): expecting pktBufs packet.MIC to be a Buffer length=4

I can send you the packet and keys if you want. It was a 28 byte payload that should have had GPS readings. A friend has just put up a LoraWAN gateway, and was receiving my packets but I wasn't getting data from TTN, so I copied and pasted from his screen into your simulator to see if it decoded.

**Comment by tony1tf** [comment]
Another attempt with a new packet also gave the same error.
This is the packet 40 CE 18 01 26 80 00 00 01 6D BD C3 85 C1 2A A8 AF 90 A5 A8 82 96 3E DE 61 CB 5F C4
and my keys are: NwkSKey 4C28FD6ADA8A16A71EF854888B838BD8
AppSKey BEAFAB474374A9CD1EC524E7CBF0C25A

**Comment by kartben** [comment]
Can you be a bit more specific on where/how you're getting this error? Are you manipulating actual buffers, and not plain hex strings?

```
> const lora_packet = require("lora-packet");
undefined
> const packet = lora_packet.fromWire(Buffer.from("40CE180126800000016DBDC385C12AA8AF90A5A882963EDE61CB5FC4","hex"))
undefined
> packet.MIC
<Buffer 61 cb 5f c4>
> const NwkSKey = Buffer.from("4C28FD6ADA8A16A71EF854888B838BD8", "hex")
undefined
> lora_packet.verifyMIC(packet, NwkSKey)
true
```

```
$ lora-packet-decode --nwkkey 4C28FD6ADA8A16A71EF854888B838BD8 --appkey BEAFAB474374A9CD1EC524E7CBF0C25A --hex 40CE180126800000016DBDC385C12AA8AF90A5A882963EDE61CB5FC4  
decoding from Hex:  40CE180126800000016DBDC385C12AA8AF90A5A882963EDE61CB5FC4
Decoded packet
--------------
Message Type = Data
            PHYPayload = 40CE180126800000016DBDC385C12AA8AF90A5A882963EDE61CB5FC4

          ( PHYPayload = MHDR[1] | MACPayload[..] | MIC[4] )
                  MHDR = 40
            MACPayload = CE180126800000016DBDC385C12AA8AF90A5A882963EDE
                   MIC = 61CB5FC4 (OK)

          ( MACPayload = FHDR | FPort | FRMPayload )
                  FHDR = CE180126800000
                 FPort = 01
            FRMPayload = 6DBDC385C12AA8AF90A5A882963EDE
             Plaintext = 0102025802880808D5FFD17D00208A ('...X.......}. .')

                ( FHDR = DevAddr[4] | FCtrl[1] | FCnt[2] | FOpts[0..15] )
               DevAddr = 260118CE (Big Endian)
                 FCtrl = 80
                  FCnt = 0000 (Big Endian)
                 FOpts =

          Message Type = Unconfirmed Data Up
             Direction = up
                  FCnt = 0
             FCtrl.ACK = false
             FCtrl.ADR = true
```

**Comment by tony1tf** [comment]
Hi

Thanks for replying. It looks like you are getting a decode. All I get back
from the on-line decryptor at
https://lorawan-packet-decoder-0ta6puiniaut.runkit.sh is the error message
instead of the comprehensive report. The payload packet (28 bytes) comes
from a screen dump of the message received by my friend's gateway as
received by him from TTN. The secret keys are those I program into the
LoraWAN node driven from my BBC Microbit device as displayed by TTN, or in
the code on my Microbit. I copy and paste, and also tried swapping my keys
to this format { 0x4C, 0x28, 0xFD, 0x6A, 0xDA, 0x8A, 0x16, 0xA7, 0x1E, 0xF8,
0x54, 0x88, 0x8B, 0x83, 0x8B, 0xD8 }, but that seemed to upset the decoder.
Does that give you enough info to understand the problem?

Tony

**Comment by kartben** [comment]
I also used the online decoder with your packet with no problem at all prior to posting my previous comment. Have you tried just removing the blanks in the hex string?

**Comment by tony1tf** [comment]
Hi
Thank you - I did the opposite - adding spaces to the secret strings, and
that upset the decoder. Taking out the spaces in the received packet works!
It's annoying that TTN shows it in that format with spaces.
Easy when you know how!
Tony

**Comment by anthonykirby** [comment]
Hi @tony1tf,
glad that's sorted (and thank you to @kartben for the help!)
About the online decoder:  I don't maintain this, it just uses lora-packet.
Anthony
