### ISSUE TITLE
New parsed field

### ISSUE THREAD

**Issue by fabsi** [anthonykirby/lora-packet#51]
Hello,

I am working on an device which use lora.

I tried to parse the following frame : 
Message Type = Data
            PHYPayload = 6049270226BA00000340020071033500FF0101867B63F7834E04CAC51E59

          ( PHYPayload = MHDR[1] | MACPayload[..] | MIC[4] )
                  MHDR = 60
            MACPayload = 49270226BA00000340020071033500FF0101867B63F7834E04
                   MIC = CAC51E59

          ( MACPayload = FHDR | FPort | FRMPayload )
                  FHDR = 49270226BA00000340020071033500FF01
                 FPort = 01
            FRMPayload = 867B63F7834E04

                ( FHDR = DevAddr[4] | FCtrl[1] | FCnt[2] | FOpts[0..15] )
               DevAddr = 26022749 (Big Endian)
                 FCtrl = BA
                  FCnt = 0000 (Big Endian)
                 FOpts = 0340020071033500FF01

          Message Type = Unconfirmed Data Down
             Direction = down
                  FCnt = 0
             FCtrl.ACK = true
             FCtrl.ADR = true

It seems that the field FPending in FCtrl is missing.

Could you help on that?

Regards,

**Comment by anthonykirby** [comment]
it looks like FPending is being decoded (e.g. see `getFCtrlFPending` in the source) but it's missing from the documentation & the text output

I'll fix this

**Comment by anthonykirby** [comment]
https://github.com/anthonykirby/lora-packet/pull/52
