### ISSUE TITLE
After FCNT crosses 65535, MIC Matched, but decryption of data is wrong

### ISSUE THREAD

**Issue by mightChamp** [anthonykirby/lora-packet#57]
Till 65535, decryption of data is perfect, but after rollover, MIC packet matched, but decryption goes wrong, I think it is due to not taking fcnt as 32bit after rollover (i.e. if after rollover value of FCNT is 10, then 65545, value of FCNT should take for decryption.

Thank You

**Comment by anthonykirby** [comment]
Hi @mightChamp 
only the lower bytes are sent on the wire - the application needs to keep track of & supply the upper bytes.  There's an optional parameter (`FCntMSBytes`) in the API for validateMIC/calculateMIC etc to do this. 

Are you setting `FCntMSBytes`?  

If you did set `FCntMSBytes` and it still doesn't work then I can happily fix the code, but (as I explain in the docs) I need some example data to be able to do this.

**Comment by anthonykirby** [comment]
@mightChamp could you confirm whether using FCntMSBytes fixes your problem?  Is it OK to close this issue?

**Comment by mightChamp** [comment]
Sorry for late response it solve my problem.
Thank you
