### ISSUE TITLE
Construct a packet with no payload

### ISSUE THREAD

**Issue by larkolab** [anthonykirby/lora-packet#6]
Hello Anthony,

And first of all, things for this library, it's great! :)

I'm trying to use it with Node-Red do do a minimal LoRaWAN server, and I'm trying to send a downlink packet to respond to a "Confirmed Data Up".
This kind of response does not require a FRMPayload, and so does not require a FPort.

But I can't find the way to specify such a packet to the  fromFields() function.
When I set the 'payload' field empty, I still get the FPort set. Can we avoid it?

My code is like:
```
var constructedPacket = lora_packet.fromFields(
    {
        payload:'',
        MType: 'Unconfirmed Data Down',
        DevAddr: new Buffer('11223344', 'hex'),
        FCtrl: {
            ADR: false,       // default = false
            ACK: true,        // default = false
            ADRACKReq: false, // default = false
            FPending: false   // default = false
        },
        FCnt: new Buffer('0000', 'hex'), // can supply a buffer or a number
    },
    null,
    new Buffer("2B7E151628AED2A6ABF7158809CF4F3C", 'hex') // NwkSKey
);
```
And I get the frame:
YK8BzAAgAAABmjJuDQ==

> ( MACPayload = FHDR | FPort | FRMPayload )
>  FHDR = AF01CC00200000
>  FPort = 01
>  FRMPayload = 

It's not really critical, but we could avoid this extra-byte for FPort. Is that possible?

Thanks a lot

**Comment by anthonykirby** [comment]
done - thank you for the suggestion!
Ant

**Comment by larkolab** [comment]
great, thanks! :)
