### ISSUE TITLE
Buffer Deprecation Warning

### ISSUE THREAD

**Issue by RicardoStoklosa** [anthonykirby/lora-packet#79]
Hi,

the lora-packet is raising a DeprecationWarning, as shown in following the image
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/16613742/157293868-29ad8e93-ef2c-4c59-8d99-d5757c8eca22.png">

This is due to the node-aes-cmac lib that uses the deprecated Buffer constructor. There is a PR in the [original repo](https://github.com/allan-stewart/node-aes-cmac) fixing this, but was completely ignored. The last update was 7 years ago.

One possible solution is to use [aes-cmac](https://www.npmjs.com/package/aes-cmac). This is a typescript implementation of node-aes-cmac.

**Comment by anthonykirby** [comment]
fixed by #80 and released as #81
