### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by SergeySKM** [anthonykirby/lora-packet#96]
Hello, 
I've installed lora-packet on Ubuntu 2204

npm -v
9.2.0
node -v
v19.3.0

npm install --no-fund lora-packet
up to date, audited 19 packages in 2s

when i try to run command-line packet decoding
e.g. 
~$lora-packet-decode --hex 40F17DBE4900020001954378762B11FF0D
~$lora-packet-decode: command not found

what am I doing wrong?

**Comment by anthonykirby** [comment]
Thank you for your clear description of the problem :grinning: 

Try `./node_modules/.bin/lora-packet-decode --hex 40F17DBE4900020001954378762B11FF0`

Here's some documentation that mentions the .bin folder: https://docs.npmjs.com/cli/v9/configuring-npm/folders#executables
